runtime: python37
service: example-pypi-server

entrypoint: gunicorn -b :8081 -w 2 'main:get_app()'

instance_class: F2

env_variables:
  BUCKET_NAME: "testing-example-pypi"
  LOCAL_PACKAGE_DIRECTORY: "/tmp"
  REMOTE_PACKAGE_DIRECTORY: "packages"
  TIER: "stg"

handlers:

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
